spring.application.name=render-example

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d7urvht0lvsc7384f1u0-a/devopsapp_bd5z}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:devopsapp_bd5z_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sFuRRzLWcamivxjU9cOMPMbT0F42Psgw}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true